### ISSUE TITLE
Bug delete last input

### ISSUE THREAD

**Issue by redXawn** [bachdgvn/vue-otp-input#1]
if you input a lot of number and exceed the limit
the last number and the first number can't be deleted

**Comment by requiem202** [comment]
I ran into this too today
Fixed it by moving Backspace and Delete to KeyUp instead (of KeyDown).


Hope this help.

**Comment by haripermadi** [comment]
> I ran into this too today
> Fixed it by moving Backspace and Delete to KeyUp instead (of KeyDown).
> 
> Hope this help.

Hi, could you provide the code?
thanks

**Comment by ChadTaljaardt** [comment]
Fixed it in the above PR if any of you want it.

**Comment by bachdgvn** [comment]
Thanks @ChadTaljaardt for your support. I merged your pull request and now this bug is resolved.

**Comment by bachdgvn** [comment]
Thanks @ChadTaljaardt for your support. I merged your pull request and now this bug is resolved.
