### ISSUE TITLE
Update gif on readme to disallow letters

### ISSUE THREAD

**Issue by ChadTaljaardt** [bachdgvn/vue-otp-input#24]
Update the gif on the readme to disallow "a,b,c,d" which it currently shows.

**Comment by bachdgvn** [comment]
OK. I will update soon 💃

**Comment by bachdgvn** [comment]
Hi @ChadTaljaardt, I haved updated the gif :))

**Comment by ChadTaljaardt** [comment]
Nice, thanks!
