### ISSUE TITLE
Allow autofill on mobile devices

### ISSUE THREAD

**Issue by liambarr** [bachdgvn/vue-otp-input#25]
Adding:  `autocomplete="one-time-code"` to an input HTML object would allow the input to be prefilled when text message arrives. Can this functionality be added to the vue-otp-input?

**Comment by bachdgvn** [comment]
Hi @liambarr,
If you want to fill the otp-input with your one time code, pls split your one time code to an array.
So you can apply this array to the $refs value: 
Ex:
`this.$refs.otpInput.otp = [1, 1, 1, 1];`

**Comment by menepet-wind** [comment]
I did the same with an alternative way ...

```
for (let i = 0; i < otpCode.length; i++) {
    this.$refs.otpInput.handleOnChange(otpCode[i])
}
```
