### ISSUE TITLE
Not accepting numbers from numeric keypad in external keyboard

### ISSUE THREAD

**Issue by hari03** [bachdgvn/vue-otp-input#26]
Vue Version - 2.5.17

How To Reproduce:
1. Install the plugin following the steps mentioned. Nothing different. 
2. Try keying in the inputs from the numeric keypad, preferably from an external keyboard.

**Comment by ChadTaljaardt** [comment]
This should have been fixed here: https://github.com/bachdgvn/vue-otp-input/pull/23

Can you pull the repo locally and test it to see if it works.

**Comment by bachdgvn** [comment]
Hi @hari03, we updated #23 in the v1.0.7. This will resolve your bug.
