### ISSUE TITLE
Can I get this working with Vuetify?

### ISSUE THREAD

**Issue by gadelkareem** [bachdgvn/vue-otp-input#27]
I am trying to get this plugin to work with https://vuetifyjs.com/en/ but I think it needs to work with the components provided from Vuetify to match the style. Can you give it a try and let me know if it is possible?

**Comment by bachdgvn** [comment]
Could you describe more about your request?

**Comment by gadelkareem** [comment]
yes sorry added.

**Comment by bachdgvn** [comment]
Sorry @gadelkareem, I don't intend to provide vue-otp-input as Vuetify's style. We build the plugin for every people that work on many design system as possible. So we must keep it simple. But you can clone and try it.
