### ISSUE TITLE
Can we have auto focus button on complete?

### ISSUE THREAD

**Issue by narendra15** [bachdgvn/vue-otp-input#33]
I am unable to use tab to focus submit button on completion of otp input.

**Comment by hacknug** [comment]
> I am unable to use tab to focus submit button on completion of otp input.

Same here. Preventing TAB and ENTER key presses is bad for UX. Users expect to be able to tab through forms and submit pressing enter.

@bachdgvn I can open a PR with the changes addressing this issue if you want :+1:
