### ISSUE TITLE
Add support for left and right arrow key to move between OTP Input fields

### ISSUE THREAD

**Issue by pratik149** [bachdgvn/vue-otp-input#36]
I tried switching back and forth the input fields using right and left arrow keys, but it didn't work. It will be good to have to this support from UX perspective.

**Comment by hacknug** [comment]
> I tried switching back and forth the input fields using right and left arrow keys, but it didn't work. It will be good to have to this support from UX perspective.

I believe this is how this plugin used to work but a regression was introduced in fa0ad5dfe1ab08d265b6ce714102c2fea0930279 when trying to make sure users weren't entering unwanted characters.

@bachdgvn I can open a PR with the changes addressing this issue if you want :+1:
