### ISSUE TITLE
Any way to clear pin

### ISSUE THREAD

**Issue by KingWu** [bachdgvn/vue-otp-input#5]

**Comment by ChadTaljaardt** [comment]
You mean some functionality where you can press a button to clear the pin?

**Comment by KingWu** [comment]
i mean any ways to force to clear the pin by a clear function

**Comment by KingWu** [comment]
eg. vueOtpInput.clear()

**Comment by Ryanalfarisi** [comment]
@KingWu  you can set like this `this.$refs.voi.otp = []` but sure, please add ref in the component like this 
`<voi
                      :numInputs="6"
                      ref="voi"
                      separator=""
                      :shouldAutoFocus="true"
                      @on-complete="handleOnComplete"
                      @on-type="handleOnType"
                    />`

**Comment by bachdgvn** [comment]
@KingWu, you can follow @Ryanalfarisi's guide. I think this solution is quite good and we do not need a method to clear pin.
Thanks @Ryanalfarisi for your support.
