### ISSUE TITLE
How to clear input?

### ISSUE THREAD

**Issue by DeloarBP** [bachdgvn/vue-otp-input#8]

**Comment by bachdgvn** [comment]
Pls, add a description for a missing so that I can re-produce and fix it.

**Comment by DeloarBP** [comment]
Dear @bachdgvn,
Actually before I didn't interpreted the issue clearly.
What I wish to do is: Lets say input has values like "3 4 5 1". And I want to clear them programmatically. Please help how can I clear input values.

**Comment by ChadTaljaardt** [comment]
Here is a pr with the fix https://github.com/bachdgvn/vue-otp-input/pull/18

**Comment by bachdgvn** [comment]
@DeloarBP, I have updated some code to help you clear the inputs programmatically, please follow the example code on README.md

Thanks for @ChadTaljaardt's contribution.
